### ISSUE TITLE
Disable ReadTheDocs project

### ISSUE THREAD

**Issue by mwatts15** [openworm/openworm_docs#101]
We've been building the docs site using general purpose CI tools for a few years now, but the RTD site is still active. It should be disabled.

*I'm adding this just so there's documentation. I am disabling the RTD build now.*

**Comment by mwatts15** [comment]
I disabled the "master" and "latest" versions.
FYI @pgleeson

**Comment by pgleeson** [comment]
Thanks for following up on this @mwatts15!

**Comment by mwatts15** [comment]
I'm not sure if we want to *delete* the project on RTD, so I left that. I'm not sure how to set up a redirect either.
