### ISSUE TITLE
Information on Release 5 (and possibly 6) missing

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/openworm_docs#19]
Currently [the release documentation](http://docs.openworm.org/en/latest/releases.html#releases) does not include Release 5, which wrapped in January 2014.

When release 6 is complete (soon?), that should be added also.

**Comment by slarson** [comment]
Started to be addressed in #29 [here](http://docs.openworm.org/en/latest/releases/) but more still needed....

**Comment by MichaelCurrie** [comment]
This is now handled: release 5,6,7 information is present at http://docs.openworm.org/en/latest/releases/
