### ISSUE TITLE
Movement directory orphaned

### ISSUE THREAD

**Issue by travs** [openworm/openworm_docs#24]
The posts inside [the movement directory](https://github.com/openworm/openworm_docs/tree/master/docs/Movement) (not to be confused with [the `worm-movement` project page](https://github.com/openworm/openworm_docs/blob/master/docs/Projects/worm-movement.md)) are not linked to from within the docs, effectively making them undiscoverable.

Should these be removed, or just linked to from somewhere in the docs?

**Comment by slarson** [comment]
@MichaelCurrie @JimHokanson Can you guys transition the content here: https://github.com/openworm/openworm_docs/tree/master/docs/Movement into the movement_validation project?  We will keep the high level pointers here to that, but I feel this stuff is stale here and better archived over in your repo.

**Comment by MichaelCurrie** [comment]
OK I've moved the content to Google Drive, at [`Movement Analysis/Archive/2013-09 - Initial notes on Schafer Lab Data/`](https://drive.google.com/folderview?id=0B9dU7zPD0s_LR3BOMksxX1BkZkk&usp=sharing).

I also refreshed the worm-movement project page with updated information.

Handled by f150099ecddd15aff409073aa26424b2138f58c1.
