### ISSUE TITLE
Update repositories.md

### ISSUE THREAD

**Issue by slarson** [openworm/openworm_docs#32]
It is getting stale

**Comment by MichaelCurrie** [comment]
I updated the movement analysis repositories by just linking to our project page.

https://github.com/openworm/openworm_docs/blob/master/docs/Community/repositories.md

**Comment by MichaelCurrie** [comment]
I added @casperdcl 's image to https://github.com/openworm/openworm_docs/blob/master/docs/Community/repositories.md.  I'll use this as an excuse to close this 4-year-old issue.

**Comment by casperdcl** [comment]
lol don't worry it's all going to change now :) #58 will automate all this

**Comment by casperdcl** [comment]
also it's weird to add my name on the website just for that graph. also I should've been more explicit:

igraph.org doesn't produce nice org repo graphs; it's just a basic python graph package. I parsed all the `.openworm.yml` files in all @OpenWorm repos and looked at the `children` and `parent` keys to construct said graph. Really in #58 or later I'd shove igraph into plotly to give a nice interactive publication-ready output.

**Comment by casperdcl** [comment]
also seems to complement/conflict/duplicate/be similar to/link with https://github.com/openworm/openworm_docs/blob/master/docs/projects.md

**Comment by casperdcl** [comment]
an finally... http://docs.openworm.org/en/latest/Community/repositories/ doesn't seem to be updated despite the fact that https://dev-openworm-docs.readthedocs.io/en/latest/Community/repositories/ has been updated. @mwatts15 any idea what's going on? I've cleared my browser cache and as per my understanding those two URLs should be displaying exactly the same site...

**Comment by mwatts15** [comment]
I have no control over that site, @casperdcl .

**Comment by pgleeson** [comment]
Looks like https://docs.openworm.org/Community/repositories/ is up to date. Closing in favour of more specific issues.
