### ISSUE TITLE
Find way to embed dynamic list of git repos / milestones / issues

### ISSUE THREAD

**Issue by slarson** [openworm/openworm_docs#33]
This should be possible via their API to have a widget that does this.  Then it would never be out of date....  Would be helpful for repositories.md and for project pages.

**Comment by pgleeson** [comment]
Repo info is updated on https://docs.openworm.org/Community/repositories/. Milestones and issues are probably better tracked/listed via github projects etc. e.g. https://github.com/orgs/openworm/projects rather than embedding in the docs site.
