### ISSUE TITLE
Broken link in Community Overview page

### ISSUE THREAD

**Issue by cheelee** [openworm/openworm_docs#38]
In http://docs.openworm.org/en/0.9/community/ , the URL for "a project" in the text "One way is to use this documentation to find a project you want to contribute to." uses the link "http://docs.openworm.org/en/0.9/Projects" instead of "http://docs.openworm.org/en/0.9/projects"

If I am not mistaken the "URLs" used under this documentation framework gets processed, and is case-sensitive unlike "real" URLs.

**Comment by pgleeson** [comment]
Fixed on live
