### ISSUE TITLE
Outdated Data Collection and Representation repo links

### ISSUE THREAD

**Issue by FelixGifford** [openworm/openworm_docs#53]
The section ["Data Collection and Representation"](http://docs.openworm.org/en/latest/Community/repositories/#data-collection-and-representation) in the Community/Repos section of the documentation contains links to repos that no-longer exist. These are:

- `NEURONSimData` (https://github.com/openworm/NEURONSimData)
- `data-viz` (https://github.com/openworm/data-viz)

The `data-viz` repo is also listed twice, along with the `wormbrowser` and `openwormbrowser-ios` repos. (Should that be a separate issue?)

**Comment by mwatts15** [comment]
Thanks, @FelixGifford ! I've removed those links.
