### ISSUE TITLE
add CI

### ISSUE THREAD

**Issue by casperdcl** [openworm/openworm_docs#56]
add continuous integration testing.

Presumably currently the site is built automatically by readthedocs.org (without build status feedback on GitHub). Adding our own CI tests means:

- can easily get build status feedback (e.g. on PRs) before merging
- can use said CI later to also automate crawling as per #55
- could potentially publish the site directly from CI from an env which we fully control

**Comment by casperdcl** [comment]
@cheelee as discussed please add push access to this repo for user @openworm-bot

**Comment by cheelee** [comment]
Done. Does it work?

**Comment by casperdcl** [comment]
yes but I think as per https://help.github.com/en/articles/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level I think it'll need admin access to this repo to modify webhooks. Hopefully the list of permissions doesn't look to scary to you (esp if you can just enable it only for this repo)

**Comment by cheelee** [comment]
Ok I've set it to the highest level of permissions for the repo - Maintain.

**Comment by casperdcl** [comment]
hmm interesting - can't it be changed to maintain? The circleci.com list of repos I can enable CI on using the bot account is currently empty

**Comment by casperdcl** [comment]
I meant Admin?

**Comment by cheelee** [comment]
Maybe I do not have those permissions. @slarson  - are you able to assign admin permissions to bot accounts specific to just this repo?

@casperdcl - are you aware of what specific capabilities the account must have to perform its tasks? When I set it to Maintain, it indicated the account would have the permission to push and change repo settings.

**Comment by cheelee** [comment]
Ok nevermind, for some reason I didn't see there was another entry below Maintain earlier. I have set it to Admin for the repo now.

**Comment by casperdcl** [comment]
kewl yes unfortunately as per the table on https://help.github.com/en/articles/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level it has to be admin for webhooks :/

**Comment by cheelee** [comment]
Ok wait. I am a little confused now. Does that mean @openworm-bot will need to be added to the organization as a member?

**Comment by balicea** [comment]
@casperdcl I am trying to solve the problem you had earlier with providing admin privileges for webhooks. I am unsure of what the solution is other than adding @openworm-bot as a collaborator for a specific repository with Admin privileges. It seems as each repo has its own webhooks.

**Comment by casperdcl** [comment]
@balicea yes that's right.

I'd think org membet with as little privileges as possible, plus admin on the docs repo.

Could just do admin collaborator if you prefer.

Also let me know how you'd like me to send you guys the login details for the bot.

**Comment by casperdcl** [comment]
managed to set up the webhook and even made a quick configuration (#57)
