### ISSUE TITLE
use gh-pages

### ISSUE THREAD

**Issue by casperdcl** [openworm/openworm_docs#60]
## currently

- commits to `master` trigger readthedocs.io to build the site and deploy to https://dev-openworm-docs.readthedocs.io/
  + we have no complete control of the build environment (only can configure via [docs/readthedocs.yml](https://github.com/openworm/openworm_docs/tree/master/docs/readthedocs.yml))
  + there's no way to tell if merging a PR will break the build
  + `mkdocs` is used as a driver to build the static html pages which are actually served
- http://docs.openworm.org is configured to point to readthedocs.io
- readthedocs.io is configured to expect http://docs.openworm.org
- the original https://openworm-docs.readthedocs.io/ is unmodifiable due to lack of permissions due to lack of response from original maintainer(s) so we're using https://dev-openworm-docs.readthedocs.io/

## proposed

- see #61

The only thing missing is:

+ [x] http://docs.openworm.org is configured to point to github.io
    * update openworm.org's CNAME DNS record for the docs subdomain to point to openworm.github.io as per https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site (i.e. make docs.openworm.org point to openworm_docs). To be very explicit @mwatts15 & @slarson atm openworm.org should have a DNS record (in hostway.net?) saying something like "docs.openworm.org CNAME openworm.readthedocs.org" which now needs to be "docs.openworm.org CNAME openworm.github.io"

This will remove the dependency on readthedocs.io servers without modifying the look of the website.

- fixes #64

**Comment by casperdcl** [comment]
@cheelee @mwatts15 let me know if this sounds reasonable.

I'd have to first enable gh-pages deployment (trivial and won't affect anything), then you can update openworm.org's CNAME DNS record for the docs subdomain as per https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site (i.e. make docs.openworm.org point to openworm_docs.github.io)

**Comment by casperdcl** [comment]
re-opening as still waiting for (from #61):

+ [ ] http://docs.openworm.org is configured to point to github.io
    * update openworm.org's CNAME DNS record for the docs subdomain to point to openworm.github.io as per https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site (i.e. make docs.openworm.org point to openworm_docs)

**Comment by casperdcl** [comment]
Note that "fix CI `mkdocs gh-deploy` permissions" (upstream https://github.com/mkdocs/mkdocs/issues/1898) is circumvented by using https instead of ssh (https://github.com/openworm/openworm_docs/commit/e85a00793c0cac4d311f3483651b817e45371442)

**Comment by casperdcl** [comment]
ping:

> To be very explicit @mwatts15 & @slarson atm openworm.org should have a DNS record (in hostway.net?) saying something like "docs.openworm.org CNAME openworm.readthedocs.org" which now needs to be "docs.openworm.org CNAME openworm.github.io"

**Comment by mwatts15** [comment]
The `gh-pages` branch is now being served at docs.openworm.org. We're still building on readthedocs.org: probably will hold onto that for a little while since I can look at multiple branches' documentation that way without building it myself, which could be convenient if multiple docs updates are happening simultaneously.

**Comment by casperdcl** [comment]
ah you mean you're using readthedocs for the purposes of previewing what will happen to `gh-pages`? Nice.

**Comment by mwatts15** [comment]
@casperdcl pretty much, yes. I'm not totally convinced that building the docs site on our own CI is ideal -- it opens up additional concerns (like security of the build) that I didn't have to worry about with just RTD, so I'm also keeping those builds operational so we can switch back if the `gh-pages` workflow becomes more trouble than it's worth to manage.
