### ISSUE TITLE
website not updated from this repo

### ISSUE THREAD

**Issue by casperdcl** [openworm/openworm_docs#64]
from https://github.com/openworm/openworm_docs/issues/32#issuecomment-545651539

Surely

http://docs.openworm.org/en/latest/Community/repositories/

should be the same as readthedocs set up by @mwatts15

https://dev-openworm-docs.readthedocs.io/en/latest/Community/repositories/

As of now, docs.openworm.org does not seem to reflect the state of this repo at all.

Also, how is the root openworm.org site (without the docs prefix) being built?

**Comment by mwatts15** [comment]
The website is a served by Github Pages.

**Comment by casperdcl** [comment]
ah so the root site is https://github.com/openworm/openworm.github.io - but what about the docs subdomain?

**Comment by mwatts15** [comment]
@casperdcl  https://openworm.readthedocs.io/en/latest/

**Comment by casperdcl** [comment]
ok, and how is that updated? is there a repo somewhere?

**Comment by casperdcl** [comment]
NB #60 would make this issue redundant (i.e. it would fix this issue)

**Comment by mwatts15** [comment]
docs.openworm.org is now serving the site built by the mkdocs Github Action.
