### ISSUE TITLE
preview site build

### ISSUE THREAD

**Issue by casperdcl** [openworm/openworm_docs#66]
from https://github.com/openworm/openworm_docs/pull/61#issuecomment-546888688

Currently it's not easy to view Circle-CI built versions of the site (PRs and branches)

**Comment by mwatts15** [comment]
This is especially useful for users who don't have or don't have time for setting up the docs build environment, but who we want to review the docs before a release.

**Comment by pgleeson** [comment]
@casperdcl @mwatts15 Is this still relevant given move to gh actions?

**Comment by casperdcl** [comment]
I think currently the "preview" is provided by readthedocs while the "live" version is server by gh-pages so this issue is outdated.

**Comment by pgleeson** [comment]
Thanks @casperdcl. Nice to see my WIP branch can be previewed there too: https://openworm.readthedocs.io/en/docs_2021_updates/
