### ISSUE TITLE
skip daily gh-pages deployment

### ISSUE THREAD

**Issue by casperdcl** [openworm/openworm_docs#75]
- `gh-pages` still gets re-deployed daily solely due to date updates
- also need to remove `*.md.template` files from the deployment

**Comment by pgleeson** [comment]
Seems to be updating twice a day now: https://github.com/openworm/openworm_docs/blob/master/.github/workflows/mkdocs.yml#L6

Any need for this @mwatts15? Unfortunately the subprojects aren't changing that fast...

**Comment by mwatts15** [comment]
I just picked that rate arbitrarily. I'm sure I can improve the skip logic.
I'll look into it this weekend at the latest.

**Comment by mwatts15** [comment]
OK, so I *did* forget about this weekend before last, but still intending to address it.

**Comment by mwatts15** [comment]
I added some logic to skip builds if repo metadata (.openworm.yml files) haven't changed and the master branch is the same as the last build. The build seems to be only updating for cause so far. I'll leave this for another day. If no unnecessary builds happen, I'll close.

**Comment by pgleeson** [comment]
@mwatts15 I've merged a PR to master and also made some commits directly to master, and the live page is not updating with any of the changes. Is the deployment only taking place if a  .openworm.yml file has been changed?

**Comment by mwatts15** [comment]
No, the logic of when to push is correct: we check if the branch is different from what's deployed and only skip if it's the same. Apparently, I was overwriting the updated site with a git stash I was doing. I've fixed that bit.

**Comment by pgleeson** [comment]
Thanks @mwatts15 that looks like it resolved the deploy issue. It does still seem to be running the action to check 4 times an hour though. While it's just a brief run, it probably only needs to be done at most once a day.

**Comment by mwatts15** [comment]
I reset it to hourly. I want a build often enough that repository metadata changes show up during the day.
